# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_controle.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 191)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.entradaTaxa = QtWidgets.QLineEdit(self.tab)
        self.entradaTaxa.setObjectName("entradaTaxa")
        self.gridLayout.addWidget(self.entradaTaxa, 1, 1, 1, 1)
        self.entradaPorta = QtWidgets.QLineEdit(self.tab)
        self.entradaPorta.setObjectName("entradaPorta")
        self.gridLayout.addWidget(self.entradaPorta, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botaoConectar = QtWidgets.QPushButton(self.tab)
        self.botaoConectar.setObjectName("botaoConectar")
        self.horizontalLayout_2.addWidget(self.botaoConectar)
        self.botaoDesconectar = QtWidgets.QPushButton(self.tab)
        self.botaoDesconectar.setCheckable(False)
        self.botaoDesconectar.setObjectName("botaoDesconectar")
        self.horizontalLayout_2.addWidget(self.botaoDesconectar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acionarD0 = QtWidgets.QRadioButton(self.tab_3)
        self.acionarD0.setObjectName("acionarD0")
        self.horizontalLayout_3.addWidget(self.acionarD0)
        self.acionarD1 = QtWidgets.QRadioButton(self.tab_3)
        self.acionarD1.setObjectName("acionarD1")
        self.horizontalLayout_3.addWidget(self.acionarD1)
        self.acionarD2 = QtWidgets.QRadioButton(self.tab_3)
        self.acionarD2.setObjectName("acionarD2")
        self.horizontalLayout_3.addWidget(self.acionarD2)
        self.acionarD3 = QtWidgets.QRadioButton(self.tab_3)
        self.acionarD3.setObjectName("acionarD3")
        self.horizontalLayout_3.addWidget(self.acionarD3)
        self.acionarD4 = QtWidgets.QRadioButton(self.tab_3)
        self.acionarD4.setObjectName("acionarD4")
        self.horizontalLayout_3.addWidget(self.acionarD4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.acionarA0 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA0.setObjectName("acionarA0")
        self.gridLayout_2.addWidget(self.acionarA0, 0, 0, 1, 1)
        self.acionarA2 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA2.setObjectName("acionarA2")
        self.gridLayout_2.addWidget(self.acionarA2, 2, 0, 1, 1)
        self.acionarA8 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA8.setObjectName("acionarA8")
        self.gridLayout_2.addWidget(self.acionarA8, 3, 1, 1, 1)
        self.acionarA1 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA1.setObjectName("acionarA1")
        self.gridLayout_2.addWidget(self.acionarA1, 1, 0, 1, 1)
        self.acionarA6 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA6.setObjectName("acionarA6")
        self.gridLayout_2.addWidget(self.acionarA6, 1, 1, 1, 1)
        self.acionarA5 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA5.setObjectName("acionarA5")
        self.gridLayout_2.addWidget(self.acionarA5, 0, 1, 1, 1)
        self.acionarA7 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA7.setObjectName("acionarA7")
        self.gridLayout_2.addWidget(self.acionarA7, 2, 1, 1, 1)
        self.acionarA3 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA3.setObjectName("acionarA3")
        self.gridLayout_2.addWidget(self.acionarA3, 3, 0, 1, 1)
        self.acionarA4 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA4.setObjectName("acionarA4")
        self.gridLayout_2.addWidget(self.acionarA4, 4, 0, 1, 1)
        self.acionarA9 = QtWidgets.QRadioButton(self.tab_2)
        self.acionarA9.setObjectName("acionarA9")
        self.gridLayout_2.addWidget(self.acionarA9, 4, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saidaSerial = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.saidaSerial.setFont(font)
        self.saidaSerial.setText("")
        self.saidaSerial.setObjectName("saidaSerial")
        self.horizontalLayout_6.addWidget(self.saidaSerial)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controle Atmega328"))
        self.label.setText(_translate("MainWindow", "Porta:"))
        self.label_2.setText(_translate("MainWindow", "Taxa:"))
        self.botaoConectar.setText(_translate("MainWindow", "Conectar"))
        self.botaoDesconectar.setText(_translate("MainWindow", "Desconectar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Conexão"))
        self.acionarD0.setText(_translate("MainWindow", "D0"))
        self.acionarD1.setText(_translate("MainWindow", "D1"))
        self.acionarD2.setText(_translate("MainWindow", "D2"))
        self.acionarD3.setText(_translate("MainWindow", "D3"))
        self.acionarD4.setText(_translate("MainWindow", "D4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Digital"))
        self.acionarA0.setText(_translate("MainWindow", "A0"))
        self.acionarA2.setText(_translate("MainWindow", "A2"))
        self.acionarA8.setText(_translate("MainWindow", "A8"))
        self.acionarA1.setText(_translate("MainWindow", "A1"))
        self.acionarA6.setText(_translate("MainWindow", "A6"))
        self.acionarA5.setText(_translate("MainWindow", "A5"))
        self.acionarA7.setText(_translate("MainWindow", "A7"))
        self.acionarA3.setText(_translate("MainWindow", "A3"))
        self.acionarA4.setText(_translate("MainWindow", "A4"))
        self.acionarA9.setText(_translate("MainWindow", "A9"))
        self.groupBox.setTitle(_translate("MainWindow", "Valor Serial:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Analógica"))

